### PR TITLE
Rename CLI executable to prefab. Fixes #60

### LINKED ISSUE #60: [DOC] Docs refer to CLI executable name `prefab`, but actual name is `cli`
**URL**
https://google.github.io/prefab/#usage

**Problem**
The documentation refers to an executable called `prefab`, however, after running `gradlew installDist` the binary which gets created is called `cli`. Additionally the output from `cli` is: 

    Usage: prefab [OPTIONS] [PACKAGE_PATH]...  

Suggest either updating docs or renaming CLI executable to `prefab`

### PR DESCRIPTION
**Pull request by dturner**

### CODE REVIEW

**Comment by dturner** [comment]
Just a quick note to say the README.md will need updating as well after this is merged.

**Comment by dturner** [comment]
@DanAlbert Any chance of merging this? I don't have write access.

**Comment by DanAlbert** [comment]
Yep, sorry. Really need to find a good autosubmit plugin.

**Comment by DanAlbert** [comment]
/gcbrun

(And misclicking on my phone seems to mean it has to run again)

**Pull request merged**
